<?php
// auto-generated by sfDatabaseConfigHandler
<<<<<<< HEAD
// date: 2014/08/08 22:50:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
=======
// date: 2014/08/14 21:31:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tesis',
>>>>>>> 944f251439e2880557d83e2a69d1253b2d83d432
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
