<?php
// auto-generated by sfDefineEnvironmentConfigHandler
<<<<<<< HEAD
// date: 2014/08/08 22:50:21
=======
// date: 2014/08/14 21:31:57
>>>>>>> 944f251439e2880557d83e2a69d1253b2d83d432
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
));
