<?php
// auto-generated by sfSecurityConfigHandler
<<<<<<< HEAD
// date: 2014/08/08 22:50:21
=======
// date: 2014/08/14 21:31:57
>>>>>>> 944f251439e2880557d83e2a69d1253b2d83d432
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
);
