<?php
// auto-generated by sfDatabaseConfigHandler
<<<<<<< HEAD
// date: 2014/08/21 17:01:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
=======
// date: 2014/08/14 21:32:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tesis',
  'username' => 'root',
  'password' => NULL,
>>>>>>> 944f251439e2880557d83e2a69d1253b2d83d432
  'name' => 'doctrine',
)),);
