<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/14 21:32:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tesis',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
