<?php
// auto-generated by sfSecurityConfigHandler
<<<<<<< HEAD
// date: 2014/08/13 22:04:51
=======
// date: 2014/08/14 21:32:17
>>>>>>> 944f251439e2880557d83e2a69d1253b2d83d432
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
);
